### ISSUE TITLE
Image Index

### ISSUE THREAD

**Issue by almgong** [AppFolioOnboarding/image-sharer-YJ83Lee#3]
#### As a user I want the homepage to display all saved images.

__Story__:

Now that we are saving images for our users, we want them to be able to view
the list of images in the system. You might be thinking, "what if my users only
want to view images of cats", or "what if my users only want to see the images
they uploaded". Those are great questions. Maybe you will have the opportunity
to add those features in a future story. For now, we will keep it simple and
quickly deliver a little more value to our users.

__Acceptance criteria__:
- [x] New images that are added show up on the homepage.
- [x] These images are persisted if the browser is closed or even if the
  server is restarted.
- [x] Images are not displayed wider than 400px.
- [x] Newest images appear first.

__Dependencies__:
- Save Image Link

**Comment by YJ83Lee** [comment]
> New images that are added show up on the homepage
> These images are persisted if the browser is closed or even if the server is restarted

The above implies that 

1. `GET /` should display all the images submitted (by providing the URL)
2. Once a URL is submitted, it is stored in the DB hence will remain intact even after server restart

> Images are not displayed wider than 400px

Simple settings in `.erb` file should suffice for now.
May not touch the CSS file yet (or are we using Sass by default?)

> Newest images appear first.

We can do the SQL query to sort them based on descending order of the timestamp.

---
To solve this issue
#### `Controller#index`
1. Use the model to retrieve all previous URLs (newest to oldest)
2. Pass the URLs to the view
#### ERB file
Display all images based on the URL

**Comment by YJ83Lee** [comment]
Will use https://www.w3schools.com/html/pic_trulli.jpg, https://www.w3schools.com/html/img_girl.jpg, and https://www.w3schools.com/html/img_chania.jpg from https://www.w3schools.com/html/html_images.asp.
